### ISSUE TITLE
Dots for displaying large REPL vectors/matrices

### ISSUE THREAD

**Issue by tclements** [wg030/jlcode#10]
Thank you for the jlcode.sty! Could \vdots, \cdots, \adots, and \ddots be included for displaying REPL outputs of large vectors and matrices?

**Comment by wg030** [comment]
I am not quite sure what you mean or rather how you intend to display REPL output, but I have added these commands with the latest update. It was a little tricky though because I had to modify the commands taken from the mathdots package in order to make them display correctly.

Maybe you can show me an example on how you use that for displaying REPL outputs!
