### ISSUE TITLE
Problem with option [usecolors=true]

### ISSUE THREAD

**Issue by jo-fleck** [wg030/jlcode#19]
@wg030 Thanks for this awesome package!

(Not sure if it's an issue or my inexperience with the package functionality.)

I am trying to typeset Julia code without a box but with colors and so in the tex preamble I am using `\usepackage[nobox=true,usecolors=true]{jlcode}`

In the pdf, there is no box but unfortunately not the colors I expected... all code is gray except numbers (they are red).

Is this caused by interference with (options of) other packages? For example, I am using the xcolor package (but without any options). Any other 'suspicious' packages I should check?

Thanks a lot for any hints and help!

**Comment by wg030** [comment]
@Jo-Fleck 
I am not sure either :D 
Your command is definitley correct and I would suspect that it has to do with package interference, but I would likely not call the xcolor package if I was asked.
Could you create a minimal working example so that I can reproduce the behaviour?

**Comment by jo-fleck** [comment]
Sure - thanks for the quick follow up!

```
\documentclass[paper=a4, fontsize=11pt]{scrartcl}
\usepackage[left=2.25cm,right=2.25cm,top=1.4cm,bottom=1.4cm,includeheadfoot]{geometry}
\usepackage[T1]{fontenc}
\usepackage{fourier}
\usepackage{amsmath,amsfonts,amsthm}
\usepackage{graphicx}	
\usepackage{url}
\usepackage{hyperref}
\usepackage{xcolor}
\usepackage{float}

\usepackage[nobox=true,usecolors=true]{jlcode}

\title{Test}
\author{Winston Smith}
\date{\today}

\begin{document}
\maketitle

\section{Julia Code in Latex}

\begin{lstlisting}
# Prepare 2004 data
df_2004 = select!(df_ASEC_2004,[:SERIAL, :RELATE, :AGE, :ADJGINC, :FILESTAT, :FILESTAT_adj]);
df_2004[!, :num] = 1:(size(df_2004,1));
hhs_2004 = unique(df_2004.SERIAL);

for k in hhs_2004

    df_tmp = df_2004[df_2004.SERIAL .== k, :]
    RELATE_vec = unique(df_tmp.RELATE)

\end{lstlisting}

\end{document}
```

The jlcode.sty file is in the same directory and the compiler doesn't throw warnings or errors. But the pdf looks like this:

<img width="782" alt="main" src="https://user-images.githubusercontent.com/25301265/84546433-a7cca280-ad01-11ea-94a7-d16455d657d0.png">

**Comment by wg030** [comment]
@Jo-Fleck 
Thanks for your example! Indeed it does not look as it should since alle keywords are not higlighted. This is not really an issue of the package however because it has to do with the typwriter font.
This has already been discuessed with a solution here #14 
Is there anything else that you miss concerning the colors?!

**Comment by jo-fleck** [comment]
Thanks so much for looking into this - much appreciated!

Adding `\renewcommand{\ttdefault}{pcr}` had no effect so here is what I did: I kept the tex file as before but added one of the lines from your `testfile.jl`. Here is the result:

![code_jlcode](https://user-images.githubusercontent.com/25301265/84959011-d205d200-b0fe-11ea-8d87-308885a34409.png)

So it seems to me this wasn't a font problem.
- Based on how Atom displays this code, I was expecting something like this:
![code_Atom](https://user-images.githubusercontent.com/25301265/84959103-feb9e980-b0fe-11ea-82f5-6a2fa3789085.png)
- This expectation was incorrect because your package has its own keyword (and color) definitions and some of the keywords in my code (`select!`, `unique`, `:Symbols`) are not included.
- But I am questioning this thinking because `unique` is in Julia base and your manual says "Moreover all keywords, literals, built-ins, macros and string types that belong to Julia's standard library were (...) included in the language definition of this package.")
-> Can you tell me what I am missing?

**Comment by wg030** [comment]
Well, @Jo-Fleck , let me answer to your post point by point:


> Adding `\renewcommand{\ttdefault}{pcr}` had no effect so here is what I did: I kept the tex file as before but added one of the lines from your `testfile.jl`. Here is the result:

Actually it should have also shown the keywords `for` and `in` with a bold font now. Hopefully you have just accidentally uploaded the wrong result image.



> * Based on how Atom displays this code, I was expecting something like this:

I see your dissapointment when this was your expectation. I am sorry to tell you that the package has not been designed like that **so far**.



> * This expectation was incorrect because your package has its own keyword (and color) definitions and some of the keywords in my code (`select!`, `unique`, `:Symbols`) are not included.

Yes, you have exactly figured it out now, though it might probably be quite unsatisfying for you. The color and keyword definitions as well as the literals are supposed to be as similar as possible to the official Julia documentation, [https://docs.julialang.org/](url). Especially functions of Julia's base like `select!` and `unique` are just displayed without any special format or color there, which I have basically just copied.



> * But I am questioning this thinking because `unique` is in Julia base and your manual says "Moreover all keywords, literals, built-ins, macros and string types that belong to Julia's standard library were (...) included in the language definition of this package.")
>   -> Can you tell me what I am missing?

Looking at my wording in the manual this sounds like a legit question. My bad, I have used an unprecise description here. I mean keywords, macros and string types should be clear, but literals and even worse built-ins are not. As explained above built-ins are not supposed to be functions, but only types, whereas literals is simply anything but a keyword, a macro, a type or a function.    
 \
 \
Well having said all this, I wil consider your issue for next update of the package, but I don't think I'll find some time for this anytime soon.
So you need to help yourself if that issue is quite important to you. But that should not be to difficult. Just look at the `jlcode.sty` and add a `morekeywords=[5]` section, where you put all the function names you need and then format them they way you like it. If you plan to do it, make use of the `createlists.jl` script provided in this package so you don't need to create alle the words manually.

**Comment by jo-fleck** [comment]
Thanks for the detailed follow up and sorry for my belated reply (busy days).

- Yes: if I include `\renewcommand{\ttdefault}{pcr}` the pdf looks like you said (bold for and in).

- Sticking to the official Julia documentation makes a lot of sense. The display in Atom is theme specific so following a single one might be confusing for users.

- (Food for thought on the way forward: Is there an easy way to integrate the color codes from one of the popular Atom themes into your package? If yes, this might save you a lot of time to expand the lists of keywords etc and give more flexibility with respect to choosing different color schemes.)

- The current output definitely serves my objective so thanks a lot for the work you already put into the package!

You clarified all my questions so I think we can close this issue.

**Comment by wg030** [comment]
Nice to hear that you are nevertheless happy with the current state of the package and
thanks for your suggestions, I will consider them for the future updates.
