### ISSUE TITLE
How to increase fonts

### ISSUE THREAD

**Issue by VivaldoMendes** [wg030/jlcode#22]
Wonderful stuff. I checked in the jlcode.sty file to see if there was an easy way to increase the size of the fonts. In some circumstances, we may need larger fonts, i.e. for slides. But I did not figure out how to do it. How can we increase the fonts' size? Thanks a lot.

**Comment by wg030** [comment]
Hi @VivaldoMendes ,
you made a good point here that I haven't considered so far. I will probably think of adding another option with my next update when I have some time again.
For a quick fix, look at line 399 of jlcode.sty. I think that modifying that to something like
`\def\jlbasicfont{\ttfamily\large\selectfont}`
should help you. However make sure that you don't use too many characters in you code per line. Printing code with a larger font size and 80 charcters per line will result in an overfull box.

**Comment by VivaldoMendes** [comment]
Thanks for the reply. However,  @leandromartinez98 had already provided some help, [here](https://discourse.julialang.org/t/what-do-you-use-to-embed-julia-code-in-latex/23992/22?u=vivmendes). Apparently, the default font is \scriptsize which turns out to be extremely small for slides,  and rather small for a Latex documentclass with 11p, or 12p.

**Comment by wg030** [comment]
Great that you have already found the solution.
Yes, the default font size is \scriptsize. The reason for this is that I use this package for displaying my julia code in an appendix exclusively, putting severeal long and complete files of code instead of small code snippets. I think that is how must people will probably use this package for and therefore this is how I designed it.
However I understand the need to display some parts of the code in a larger way, for example for presentations or maybe even as explaining some algorithms in your normal text.
I think I might go for a three way option in the next update of this packae giving the user the choice between \scriptsize code for appendices, \normalsize code for normal text and \large code for slides of a pressentation.

**Comment by wg030** [comment]
I am happy to announce that the scaling with the font size has now been solved with the latest update.
I decided to go for a solution that autoresizes the font size of the code according to the font size of the current active font.
You can now to something like `{\LARGE \jlinputlisting{filename.jl}}` and you code will be displayed larger. However please note that I created a new command `\jlinputlisting` which in analogus to `\lstinputlisting`, but needs to be called in order to resize the font.

**Comment by RainerHeintzmann** [comment]
I tried using `\jlinputlisting` but only get the error that the pdf file cannot be exported. This is reproducible. With `{\large \jlinputlisting{filename.jl}}` it works without problems, but the font-size is not quite right.

**Comment by wg030** [comment]
@RainerHeintzmann
Thanks for your post. I have not fully understood your problem yet, but reproducible problems are those that I like the most.
I would like to ask you to create a new issue with a minimal working example so that I can reproduce the error myself. I think chances are good that we will find the root of your error then.

**Comment by RainerHeintzmann** [comment]
I get the error, as soon as I am using square brackets `[`, `]` after `jlinputlisting` to specify captions etc. Even with empty ones.

**Comment by RainerHeintzmann** [comment]
I think this fixes it:
```
% defining the \jlinputlisting command for listing standalone files
\newcommand{\jlinputlisting}[2][]{%
\calcboxlengths%
\lstinputlisting[language=julia, style=jlcodestyle, #1]{#2}}
```

**Comment by wg030** [comment]
Yes, the `jlinputlisting` command has not been defined in such a way that it supports additional parameters of the listings package to be set. I will test and consider your suggested solution with the next update. Thanks for that contribution.

**Comment by wg030** [comment]
I successfully tested your modification of the `\jlinputlisting`  command and since it worked as expected, it is now part of the latest update!

**Comment by RainerHeintzmann** [comment]
Nice to hear this.
