### ISSUE TITLE
\ell character

### ISSUE THREAD

**Issue by phipsgabler** [wg030/jlcode#24]
I wasn't really sure in which section to put this, and I have no idea what the number at the end means, so no PR -- but the following works for me:

```
{ℓ}{{\ucc{$\ell$}}}{1}
```

**Comment by wg030** [comment]
This will probably lead to a new section for script letters.
Since they seem to be used, it's time to consider them with for the next update.
The {1} at the end means that the "literated" expression is supoosed to be only one single character. I think the listings package needs this information in order to reserve the correct space.

**Comment by phipsgabler** [comment]
Ah, I see!  Maybe I can make a PR when I find the time in some weeks.

I thought about the lack of script letters, but then it gets overwhelming soon.  Do you know about https://github.com/emacs-straight/math-symbol-lists?  Thats basically where I get all fancy unicode that I use in Julia from.  Perhaps it is possible to automatically convert parts of that.

**Comment by wg030** [comment]
Any support would be highly apprecitated because I don't know when I will have enough time to update the package myself.
I did not know about https://github.com/emacs-straight/math-symbol-lists, but it seems to be worth taking a closer look at. Maybe it could indeed be of some help.

**Comment by wg030** [comment]
The character has now been added together with some more new mathematical symbols with the latest update! Check it out!
