### ISSUE TITLE
\jlinl spacing does not scale with font size

### ISSUE THREAD

**Issue by phipsgabler** [wg030/jlcode#28]
MWE:

```latex
\documentclass{article}

\usepackage{listings}

\newlength{\jlinlem}
\settowidth{\jlinlem}{\texttt{m}}
\newcommand{\jlinl}[1]{\lstinline[basicstyle=\ttfamily, basewidth=\jlinlem]^^a7#1^^a7}

\begin{document}
\footnotesize  # NOTE THE SIZE!
bla

 Initialize \jlinl{new_thing()}
\end{document}
```

Without setting `basewidth`, this is looks fine: 

![image](https://user-images.githubusercontent.com/7878215/99397661-a708ef80-28e3-11eb-9024-f0ecf3c96bdf.png)

But including it, you get weird spaces:

![image](https://user-images.githubusercontent.com/7878215/99397733-bab45600-28e3-11eb-9b9a-a7fea639f548.png)

Is there a good reason for setting the basewidth explicitely?

**Comment by phipsgabler** [comment]
Oh, and the intermediate fix is of course to simply `\settowidth{\jlinlem}{\jlinlfont{m}}` in the environment where the font size is changed.

**Comment by wg030** [comment]
> Is there a good reason for setting the basewidth explicitely?

Well to answer this question first, let's have a closer look at the original code from the package:
```latex
\newcommand{\jlinl}[1]{%
\lstinline[language=julia,style=jlcodestyle,
basicstyle=\jlinlfont,basewidth=\jlinlem]^^a7#1^^a7}
```
As you can see we set `style=jlcodestyle`, which itself is defined by the package options as a composition of the different styles. But the crucial point here is that it will always contain the option `basewidth=\bfem`. Since we want to display the inline code as `\small`, there is a need to overwrite it.
As your MWE is concerned, the problem does not apply to the package due to a similar reason. The `style=jlcodestyle` option will also always contain the option `columns=fixed`. If you added this to your MWE than everything would look nice.
Or to say that differtently, the code
```latex
\documentclass{article}

\usepackage{jlcode}

\begin{document}
\footnotesize  % NOTE THE SIZE!
bla

 Initialize \jlinl{new_thing()}
\end{document}
```
produces an output that does not have the problem with the spacing as you described it.
The only thing that might not be as you would like it to be is that as of now the fontsize of the inline code in general will not scale with the fontsize of the surrounding text. However this is related to the issue #22 which I will try to tackle anyway.

**Comment by phipsgabler** [comment]
Well, in my setting, it _does_ have have problem in a non-minimal example -- that was how I found the issue.  But that's a huge document, where I have a lot of other things interacting, of course: the effect occured within an `algorithmicx` environment inside a float, with Inconsolata as typewriter font, using microtype, in memoir, and certainly other things I have forgotten.  And maybe I have changed things in jlcode which I now forgot :)  The only other options I use are `charsperline=94, usebox=false`.

Anyway, if you're working on the scaling in general, that should probably fix it.

**Comment by wg030** [comment]
The font size now scales automaticall with the font size of the current active font. So everything should be fine here.
Please check if you sill have any trouble and if yes we will have to figure out what is going on, but with all the packages you use I would assume it would very likely be a problem of interference.
