### ISSUE TITLE
Support for LuaLaTeX?

### ISSUE THREAD

**Issue by carlosal1015** [wg030/jlcode#31]
Hello, do you know how to show the math operators when is compiled with LuaLaTeX, since that with pdfLaTeX works well.

```tex
\documentclass{scrartcl}

\usepackage[autoload=true]{jlcode}

\begin{document}

Hello Julia

\jlinputlisting{testfile.jl}

\end{document}
```
![Screen Capture_select-area_20201201182744](https://user-images.githubusercontent.com/21283014/100808859-ef0b3480-3402-11eb-8457-52752970c9c3.png)

```tex
\documentclass{scrartcl}

\usepackage[autoload=true]{jlcode}

\begin{document}

Hello Julia with Lua\LaTeX.

\jlinputlisting{testfile.jl}

\end{document}
```
![Screen Capture_select-area_20201201183100](https://user-images.githubusercontent.com/21283014/100809102-69d44f80-3403-11eb-957b-d6cea1fce125.png)

**Comment by wg030** [comment]
Well, to be honest, I don't have much experience with LuaLaTeX, but I have figured out how to do it.
As far as I understand, the basic problem is that LuaLaTeX handles utf-8 characters differently than pdflatex. The  listings package was desgined at a time where people did not care about those characters. This is also the reason why we must literate those characters here.
What you would need to do for LuaLaTeX besides literating is telling the listings packages that it can safely process those characters. You can do it like this (I did it for a few characters to show you the effect) by adding the following lines to the preamble of your document (or modifying the jlcode pakcage).

```
\makeatletter
\lst@InputCatcodes
\def\lst@DefEC{%
 \lst@CCECUse \lst@ProcessLetter
  ^^^^00dc% Ü
  ^^^^00f6% ö
  ^^^^00df% ß
  ^^^^00e4% ä
  ^^^^20ac% €
  ^^^^03b1% α
  ^^^^03b2% β
  ^^^^03b3% γ
  ^^^^00b2% ²
  ^^^^0394% Δ
  ^^^^2093% ₓ
  ^^^^0308% two dots above
  ^^^^03a5% Υ
  ^^^^212f% ℯ
  ^^^^0303% tilde above
  ^^^^00d7% ×
  ^^^^00f7% ÷
  ^^^^2286% ⊆
  ^^00}
\lst@RestoreCatcodes
\makeatother
```
The bad news of course is that you would need to add each unicode character that your code uses separatley if you really wanted to make that effort. The page www.compart.com might be helpful in order to get the correct utf encodings for all those characters.

**Comment by wg030** [comment]
**I am happy to announce that since the latest version 6.0 there is now support for LuaLaTeX (as well as XeLaTeX)!**

I wrote the script _createucclist.jl_, which can create all tex encodings for the most common Unicode characters so that I could add them easily to this package as shown in my small example above.
Moreover we make use of the new JuliaMono font (https://github.com/cormullion/juliamono), so that we esentially have all important Unicode characters.
When compiling your document with LuaLaTeX there is nothing speical to do other than putting the JuliaMono-*.tff files into the directory of your tex document or setting `\usepackage[defaultmonofont=false]{jlcode}` and going with whatever font you like the most. However, make sure that the font supports the Unicode characters that appear in your code.

**Comment by carlosal1015** [comment]
Thank you very much @wg030. I will try soon.
