### ISSUE TITLE
Keep getting Package Listings Error

### ISSUE THREAD

**Issue by rs7q5** [wg030/jlcode#33]
I think I am doing something wrong, but can't figure out for the life of me why this isn't working. 

In the preamble I have :
``
\let\Bbbk\relax                                     %I get a \Bbbk error if I don't have this before 
\usepackage[autoload=false]{jlcode}
``

And then in the document/chapter I have:
``
\jlinputlisting[language=julia, style=jlcodestyle]{code.jl}
``
The error I get is
``
Package Listings Error: File `[(.tex)' not found. \jlinputlisting[
``

The .jl file was initially in a separate directory so on the off chance it was throwing an error I copied it into the same directory. 

Any thoughts on what the issue may be?

**Comment by wg030** [comment]
I am not sure what might go wrong here.
If you have the `jlcode.sty` file in the same directory as your `mytexfile.tex` as well as your `code.jl` file, everything should be fine.
Could you post a minimal working example of your tex file? Maybe we can figure out what happens then.

**Comment by rs7q5** [comment]
I am using a different document class, etc. but below is a MWE that reproduced the same error. The tex code does say something about cannot \read from terminal in nonstop modes. 

If you need the .jl file let me know. I even tried adding the jlstyle directly into the same folder and no luck. 

``
\documentclass[12pt]{article}

 %more math symbols/bold symbols
\usepackage{amsmath}

% importing codes
% This provides settings and stuff to insert MATLAB code into file
% \usepackage{listings} %does not include julia (jlcode loads listings itself, so may not need to explicitly add)
\let\Bbbk\relax %relaxes Bbbk defined in amssymb as is defined in another package
\usepackage[autoload=false]{jlcode} %https://github.com/wg030/jlcode

\begin{document}
	\jlinputlisting[language=julia, style=jlcodestyle]{symseqSandbox.jl}
\end{document}

``

**Comment by wg030** [comment]
My bad!
You did everything as I showed it to you in the manual and explanations, but I made a misstake here when updating it.
With the latest update I introduced `\jlinputlisting` in order to make it more convenient for the user. In the previous version you had to write `\lstinputlisting[language=julia, style=jlcodestyle]{symseqSandbox.jl}`, but now you only need to write `\jlinputlisting{symseqSandbox.jl}` since the command is defined in such a way that it sets the `language=julia, style=jlcodestyle` automatically.
I will update the manual to the correct command with the next version. Thanks for reporting this issue!

**Comment by rs7q5** [comment]
I thought I was going crazy!  Glad it is a small fix. Will the input path option work with jlinput listing or does it assume no options? 

Thank you for quickly addressing this issue!

**Comment by rs7q5** [comment]
I seem to still be getting an error, when I run the MWE it works, but it does not work when I try to use it in an appendix for my dissertation. It is a chapter. Are there any package conflicts that could be present that I would need to remedy? 
The current error is 
``
Package Listings Error: File `symseqSandbox(.jl)' not found. \jlinputlisting{symseqSandbox.jl}
``

So it is at least recognizing .jl

**Comment by wg030** [comment]
Haha, no, you are still allright and not crazy!

```
\jlinputlisting{symseqSandbox.jl}
```

is equivalent to

```
\calcboxlengths%
\lstinputlisting[language=julia, style=jlcodestyle]{symseqSandbox.jl}
```

However you can only set the filename with `jlinputlisting`. If you require additional arguments, you will need to go with the `lstinputlisting` version.

**Comment by rs7q5** [comment]
So relative paths it is. Got it.

**Comment by wg030** [comment]
> I seem to still be getting an error, when I run the MWE it works, but it does not work when I try to use it in an appendix for my dissertation. It is a chapter. Are there any package conflicts that could be present that I would need to remedy?
> The current error is
> `` Package Listings Error: File `symseqSandbox(.jl)' not found. \jlinputlisting{symseqSandbox.jl} ``
> 
> So it is at least recognizing .jl

Hmm, that sounds as if the tex file and the `symseqSandbox.jl`  are not in the same directory?!

**Comment by rs7q5** [comment]
Except they are in the same directory. same folder actually to see if that was the issue. The jlcode.sty is in a folder above though. I tried putting it in the same folder and still nothing. 

It's probably a thing to do with my document class.... I don't think it's an issue with your implementation.

Thanks again for the help.

**Comment by wg030** [comment]
I fixed that issue with the latest update and refreshed the manual.

Ironically, I also slightliy modified the `jlinputlisting` command so that one can now add additional arguments, too, which means that now your `\jlinputlisting[language=julia, style=jlcodestyle]{symseqSandbox.jl}` would not cause an error anymore although the arguments `would language=julia, style=jlcodestyle` would be redundant since they are still set autoamatically.
However things like `\jlinputlisting[caption={My Sandbox Code}]{symseqSandbox.jl}` also work now.
