### ISSUE TITLE
Single quotes should not be treated as a string

### ISSUE THREAD

**Issue by tanhevg** [wg030/jlcode#4]
Hey,

Thanks for the package, stellar effort. One small thing I found is that it treats a single quote as a string boundary. This upsets my listings that have matrix transpositions in them (single quote is really a transposition operator in Julia).

 I have fixed it myself for now by just removing line 121 from `jlcode.sty`, but not sure if this is really the right thing to do. Would need a more thorough test set to make sure this does not brake anything.

**Comment by wg030** [comment]
Hey tanhevg,
this is a great point I have figured out lately, too, but have not found a great solution yet because single quotes can be used for characters as well as transpositions. It's difficult to somehow combine these two things.
However if you only work with the transposition, your are absolutley right that you have to remove line 121 from `jlcode.sty`, but you should also add `{'}{{{\color{jlbase}'}}}{1}` in line 236, so that the single quotes will have the right color.
I will leave this issue open until a satisfying solution has been found that can cope with both cases.

**Comment by wg030** [comment]
With the latest update I have decided that the `'` is more likely to be used for the transposition operator than for a single character so I modified the code accordingly, but I had to place the definition in line 400 so that single characters can be treated as a known managable issue.
I have demonstrated the new behaviour in my example code. Since both cases can be treated now I consider this issue as done and I will close it now.
