### ISSUE TITLE
Get utf-8 error with degree symbol

### ISSUE THREAD

**Issue by rs7q5** [wg030/jlcode#47]
I'm probably just doing something wrong, but can't get the degree symbol to show up. keep getting the latex error of invalid utf-8 byte sequence.   Any ideas on how to fix this?

**Comment by wg030** [comment]
Hi @rs7q5,
you are probably not doing anything wrong here. The degree symbol (I hope you talk about that one:`T = 22 °C`) has simply not been defined yet for compilation with pdftex because nobody has ever used that.
But I have just added it the package now. Try to download the latest version and tell me if everything works as expected now!

**Comment by rs7q5** [comment]
@wg030 it looks like that fixed it! thanks for the quick response and fix!

**Comment by rs7q5** [comment]
Is the symbol the same as using Alt+0176? I think I can't remember which degree symbol Julia technically uses it.

**Comment by wg030** [comment]
> I think I can't remember which degree symbol Julia technically uses it.

In which context do you use the degree symbol with Julia? To be honest I have never used that in Julia and don't know where it can be applied.

---

> Is the symbol the same as using Alt+0176?

Well, according to https://docs.julialang.org/en/v1.7/manual/unicode-input/  the hex code ot he Degree Sign is "U+000B0", which translates to "0176" as decimal number, so it should be the same!

**Comment by rs7q5** [comment]
I use it in comments and strings for names of things. but yeah I know julia uses that and then latex uses a variety of different symbols like \degree and stuff or \circ. I can't remember the difference there, but if it what you uses translates back to 0176 then that should be fine since it is the julia code script anyway and not latex!

**Comment by wg030** [comment]
Yes, the symbol in the Julia code is what is important here.
As a matter of fact, we could use just about any latex command to which the Julia code symbol should be translated to (in the case of pdflatex). I used `\circ`, but if you like `\degree` or anything else more due to a nicer output, feel free to change that in line `2031` of `jlcode.sty` and open a PR to share your experience!
Since the symbol in the Julia code is the right one (U+000B0 = Alt+0176), we can close this issue, I guess.

**Comment by rs7q5** [comment]
Correct, I'm not sure if you'd notice a difference in the listings to be honest. Since it should convert to Julia. 

I'll go ahead and close this issue as it is solved. Thanks again!
