### ISSUE TITLE
\pm problems

### ISSUE THREAD

**Issue by togo65** [wg030/jlcode#51]
Hi, Thank you for your brilliant package I have used it a lot. However, this doesn't work for me (it's the \pm causing the issue):
```
documentclass[12pt]{article}
\usepackage{jlcode}
\DeclareUnicodeCharacter{00B1}{\textpm}
\begin{document}
	\lstset{frameround=fttt}
	\begin{jllisting}[frame=trBL]
		using Measurements
		θ = 30 ± 5
	\end{jllisting}
\end{document}
```

I get the error: `Invalid UTF-8 byte "B1. θ = 30 ±` Note that I have attempted to define the correct unicode character. I am using pdflatex, but I have experimented with lualatex and `\usepackage{julia-mono-listings}`

**Comment by wg030** [comment]
Well, for some reason that I cannot explain myself I haven't added the plusminus symbol for pdftex.
I just updated the package and this should work now.

btw: If you miss other symbols for pdftex do not go for `\DeclareUnicodeCharacter` in your tex file since this will not work. Instead add a line of code like  `{±}{{\uccop{${\scriptstyle \pm}$}}}{1}` to the `jlcode.sty` file itself.
Moreover since the last bigger update, jlcode also works with luatex, which supports nearly all special unicode characters anybody would want to use. Hence if you can, I would recommend you to go with luatex

**Comment by togo65** [comment]
Many thanks! I will download the new `jlcode.sty` file and I will also re-try using lualatex. There were some issues around `fontenc` that I didn't understand. Thank you for the tip about adding unicode characters.  :)
